on: push
    # branches:
    #   - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    # - name: install serverless and serverless-python-requirements
    #   run: |
    #     npm install -g serverless
    #     serverless plugin install -n serverless-python-requirements
    # - name: serverless deploy
    #   uses: serverless/github-action@v3.1
    #   with:
    #     args: deploy
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}
    - name: Serverless Deploy
      uses: dhollerbach/actions.serverless-with-python-requirements@master
      with:
        args: ''  # any deploy arguments you want to pass
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}